Error: Python: Traceback (most recent call last):
  File "C:\Users\bsoo.hwang.SECDS\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\rteach\ops_teach_main.py", line 1054, in execute
    for i, bn in enumerate(bones):
                 ^^^^^^^^^^^^^^^^
TypeError: 'ValueError' object is not iterable
